server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    # Secure 256-bit signature key
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    # 3600000 ms = 1 Hour Expiry Window
    expiration-ms: 3600000